---
- name: "Include common service account tasks"
  ansible.builtin.include_tasks: common.yml
  when: security_mode | default('enforce') == 'enforce'
  tags: [enforce]

- name: "Include platform-specific service account tasks"
  ansible.builtin.set_fact:
    service_accounts_transfer_platform_task: >-
      {{
        lookup(
          'ansible.builtin.first_found',
          params={'files': [ansible_os_family | lower ~ '.yml'], 'paths': [role_path ~ '/tasks']},
          errors='ignore'
        )
      }}
  tags: [enforce]

- name: "Platform-specific service account tasks"
  ansible.builtin.include_tasks: "{{ service_accounts_transfer_platform_task }}"
  when:
    - service_accounts_transfer_platform_task is not none
    - service_accounts_transfer_platform_task | length > 0
    - security_mode | default('enforce') == 'enforce'
  tags: [enforce]
