---
- name: "RedHat | Ensure sshd binary path is present"
  ansible.builtin.stat:
    path: /usr/sbin/sshd
  register: sshd_hardening_sshd_path

- name: "RedHat | Fail if sshd not found"
  ansible.builtin.fail:
    msg: "sshd binary not found at /usr/sbin/sshd"
  when: not sshd_hardening_sshd_path.stat.exists
