---
# Auto / forced mode selection
security_capabilities_auth_mode: auto # auto|sk_keys|pam_mfa|legacy
security_capabilities_force_mode: ""
security_capabilities_force_openssh_version: ""

# Groups
security_capabilities_human_groups:
  - linux-admins
  - devops
security_capabilities_service_groups:
  - svc-automation
  - svc-transfer

# MFA behavior when SK keys are available
security_capabilities_mfa_for_humans_even_with_sk_keys: false

# Breakglass for TOTP
security_capabilities_totp_breakglass_enabled: true

# Internal capability map defaults
security_capabilities_pkg_names:
  debian: openssh-server
  ubuntu: openssh-server
  redhat: openssh-server
  rocky: openssh-server
  centos: openssh-server
