---
galaxy_info:
  author: Miguel Alpañez
  description: Minimal CIS baseline checks/enforcement for SSH and sudo.
  license: GPL-2.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions: [buster, bullseye, bookworm]
    - name: Ubuntu
      versions: [bionic, focal, jammy]
    - name: EL
      versions: [all]
dependencies: []
