---
sshd_hardening_password_authentication: false
sshd_hardening_permit_root_login: "no"
sshd_hardening_permit_empty_passwords: false
sshd_hardening_challenge_response_authentication: false
sshd_hardening_use_pam: true
sshd_hardening_x11_forwarding: false
sshd_hardening_login_grace_time: "30"
sshd_hardening_client_alive_interval: 300
sshd_hardening_client_alive_count_max: 2
sshd_hardening_max_auth_tries: 4
sshd_hardening_max_sessions: 10
sshd_hardening_max_startups: "10:30:60"
sshd_hardening_print_motd: false
sshd_hardening_use_dns: false
sshd_hardening_compression: false
sshd_hardening_banner: ""
sshd_hardening_log_level: VERBOSE
sshd_hardening_allow_users: []
sshd_hardening_allow_groups: []
sshd_hardening_human_groups: "{{ security_capabilities_human_groups | default([]) }}"
sshd_hardening_service_groups: "{{ security_capabilities_service_groups | default([]) }}"
sshd_hardening_trusted_ca_key: ""
sshd_hardening_trusted_ca_path: /etc/ssh/trusted_user_ca_keys
sshd_config_path: /etc/ssh/sshd_config
sshd_config_dir: /etc/ssh/sshd_config.d
sshd_service_name: sshd
sshd_binary_path: /usr/sbin/sshd
ssh_auth_log: /var/log/auth.log
sshd_hardening_algorithm_profile: auto
sshd_hardening_algorithm_sets:
  modern:
    ciphers:
      - chacha20-poly1305@openssh.com
      - aes256-gcm@openssh.com
      - aes256-ctr
      - aes192-ctr
      - aes128-ctr
    macs:
      - hmac-sha2-512-etm@openssh.com
      - hmac-sha2-256-etm@openssh.com
      - hmac-sha2-512
      - hmac-sha2-256
    kex_algorithms:
      - curve25519-sha256
      - curve25519-sha256@libssh.org
      - ecdh-sha2-nistp521
      - ecdh-sha2-nistp384
      - ecdh-sha2-nistp256
    hostkey_algorithms:
      - ssh-ed25519
      - rsa-sha2-512
      - rsa-sha2-256
  legacy:
    ciphers:
      - chacha20-poly1305@openssh.com
      - aes256-ctr
      - aes192-ctr
      - aes128-ctr
    macs:
      - hmac-sha2-512-etm@openssh.com
      - hmac-sha2-256-etm@openssh.com
      - hmac-sha2-512
      - hmac-sha2-256
    kex_algorithms:
      - curve25519-sha256
      - curve25519-sha256@libssh.org
      - ecdh-sha2-nistp384
      - ecdh-sha2-nistp256
    hostkey_algorithms:
      - ssh-ed25519
      - ssh-rsa
sshd_hardening_service_match_blocks: []
sshd_hardening_service_name: "sshd"
sshd_hardening_package_name: "openssh-server"
