---
_mysql_service_name: mysqld
_mysql_packages:
  - mysql-server
_mysql_conf_dir: /etc/my.cnf.d
_mysql_security_conf: /etc/my.cnf.d/99-security-hardening.cnf
_mysql_datadir: /var/lib/mysql
_mysql_error_log: /var/log/mysqld.log
_mysql_binary: mysql
