---
- name: Cis Enforce | Ensure PasswordAuthentication no
  ansible.builtin.lineinfile:
    path: "{{ cis_baseline_sshd_config_path }}"
    regexp: ^PasswordAuthentication
    line: PasswordAuthentication no
    create: true
    mode: "0600"
    owner: root
    group: root
  notify: Restart sshd
  tags: [cis_enforce]

- name: Cis Enforce | Ensure PermitRootLogin no
  ansible.builtin.lineinfile:
    path: "{{ cis_baseline_sshd_config_path }}"
    regexp: ^PermitRootLogin
    line: PermitRootLogin no
    create: true
    mode: "0600"
    owner: root
    group: root
  notify: Restart sshd
  tags: [cis_enforce]

- name: Cis Enforce | Ensure sudoers use_pty
  ansible.builtin.lineinfile:
    path: "{{ cis_baseline_sudoers_path }}"
    regexp: ^Defaults.*use_pty
    line: Defaults    use_pty
    state: present
    mode: "0440"
    owner: root
    group: root
    validate: visudo -cf %s
  tags: [cis_enforce]
