---
- name: Prepare
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Fix Rocky 9 nsswitch for sudo/PAM in containers
      ansible.builtin.replace:
        path: /etc/nsswitch.conf
        regexp: ' sss'
        replace: ''
      failed_when: false
