---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Include usbguard role
      ansible.builtin.include_role:
        name: malpanez.security.usbguard
      vars:
        usbguard_enabled: true
        security_mode: enforce
