---
- name: Converge
  hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - name: Ensure remote tmp directory
      ansible.builtin.raw: mkdir -p /tmp/ansible-tmp
      changed_when: false
    - name: Gather facts
      ansible.builtin.setup:
    - name: Create test directory for SELinux context
      ansible.builtin.file:
        path: /srv/app/data
        state: directory
        mode: "0755"

  vars:
    selinux_enforcement_enabled: true
    selinux_enforcement_mode: enforcing
    selinux_enforcement_booleans:
      - name: nis_enabled
        state: true
    selinux_enforcement_contexts:
      - target: /srv/app/data(/.*)?
        setype: public_content_rw_t
  roles:
    - role: selinux_enforcement
