---
dependency:
  name: galaxy
  options:
    requirements-file: ../../../../requirements.yml
driver:
  name: docker
platforms:
  - name: rockylinux9
    image: geerlingguy/docker-rockylinux9-ansible:latest
    platform: linux/amd64
    privileged: true
    command: /lib/systemd/systemd
    pre_build_image: true
