---
galaxy_info:
  author: Miguel Alpañez
  description: Secure service accounts for SFTP/rsync/automation with restricted SSH.
  license: GPL-2.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: all
      versions: [all]
dependencies: []
