- hosts: localhost
  gather_facts: false
  roles:
    - role: malpanez.security.sshd_hardening
---
- name: Test sshd_hardening
  hosts: localhost
  gather_facts: false
  roles:
    - role: malpanez.security.sshd_hardening
