---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify | Assert selected mode is sk_keys (forced version)
      ansible.builtin.assert:
        that:
          - security_capabilities_selected_auth_mode == 'sk_keys'
        fail_msg: Auth mode was not sk_keys as expected for forced version 8.4
