---
selinux_enforcement_enabled: false
selinux_enforcement_mode: enforcing
selinux_enforcement_booleans: []
selinux_enforcement_contexts: []
selinux_enforcement_packages:
  - policycoreutils
  - policycoreutils-python-utils
  - setools-console
selinux_enforcement_restorecon: true
