---
- name: "Skip SELinux enforcement when disabled"
  ansible.builtin.meta: end_play
  when: not selinux_enforcement_enabled

- name: "Include common SELinux tasks"
  ansible.builtin.include_tasks: common.yml
  when: security_mode | default('enforce') == 'enforce'
  tags: [enforce]

- name: "Include platform-specific SELinux tasks"
  ansible.builtin.set_fact:
    selinux_enforcement_platform_task: "{{ lookup('ansible.builtin.first_found', params={'files': [ansible_os_family | lower ~ '.yml'], 'paths': [role_path ~ '/tasks']}, errors='ignore') }}"
  tags: [enforce]

- name: "Platform-specific SELinux tasks"
  ansible.builtin.include_tasks: "{{ selinux_enforcement_platform_task }}"
  when: selinux_enforcement_platform_task is not none and security_mode | default('enforce') == 'enforce'
  tags: [enforce]
