---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Include firewall role
      ansible.builtin.include_role:
        name: malpanez.security.firewall
      vars:
        firewall_enabled: true
        security_mode: enforce
        firewall_allowed_tcp_ports: [80, 443]
        firewall_trusted_sources: ["10.0.0.0/8"]
