---
galaxy_info:
  author: Miguel Alpañez
  description: Manage SELinux mode, booleans, and contexts safely.
  license: GPL-2.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions: [buster, bullseye, bookworm]
    - name: Ubuntu
      versions: [bionic, focal, jammy]
    - name: EL
      versions: ["7", "8", "9"]
dependencies:
