---
sshd_hardening_config_path: /etc/ssh/sshd_config
sshd_hardening_config_dir: /etc/ssh/sshd_config.d
sshd_hardening_service_name: ssh
sshd_hardening_binary_path: /usr/sbin/sshd
sshd_hardening_auth_log: /var/log/auth.log
