---
- name: Converge
  hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - name: Ensure remote tmp directory
      ansible.builtin.raw: mkdir -p /tmp/ansible-tmp
      changed_when: false
    - name: Gather facts
      ansible.builtin.setup:
  roles:
    - role: sshd_hardening
