---
dependency:
  name: galaxy
  options:
    requirements-file: ../../../../requirements.yml
driver:
  name: docker
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..
  config_options:
    defaults:
      roles_path: ../../..
      remote_tmp: /tmp/ansible-tmp
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    platform: linux/amd64
    privileged: true
    command: /lib/systemd/systemd
    pre_build_image: true
  - name: debian12
    image: geerlingguy/docker-debian12-ansible:latest
    platform: linux/amd64
    privileged: true
    command: /lib/systemd/systemd
    pre_build_image: true
  - name: debian13
    image: geerlingguy/docker-debian13-ansible:latest
    platform: linux/amd64
    privileged: true
    command: /lib/systemd/systemd
    pre_build_image: true
  - name: rockylinux9
    image: geerlingguy/docker-rockylinux9-ansible:latest
    platform: linux/amd64
    privileged: true
    command: /lib/systemd/systemd
    pre_build_image: true
