---
- name: Converge
  hosts: all
  become: true
  gather_facts: false
  pre_tasks:
    - name: Ensure remote tmp directory
      ansible.builtin.raw: mkdir -p /tmp/ansible-tmp
      changed_when: false
    - name: Gather facts
      ansible.builtin.setup:
    - name: Install OpenSSH server (Debian/Ubuntu)
      ansible.builtin.apt:
        name: openssh-server
        state: present
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'
    - name: Install OpenSSH server (RedHat)
      ansible.builtin.dnf:
        name: openssh-server
        state: present
      when: ansible_facts['os_family'] == 'RedHat'
  vars:
    pam_mfa_enabled: true
    pam_mfa_totp_enabled: true
    pam_mfa_breakglass_group: mfa-breakglass
  roles:
    - role: pam_mfa
