---
ntp_hardening_enabled: false

ntp_hardening_servers:
  - 0.pool.ntp.org iburst
  - 1.pool.ntp.org iburst
  - 2.pool.ntp.org iburst
  - 3.pool.ntp.org iburst

ntp_hardening_makestep: "1.0 3"
ntp_hardening_rtcsync: true
ntp_hardening_maxdistance: 1.5
ntp_hardening_minsources: 1
ntp_hardening_allow: []
ntp_hardening_deny_all: true
ntp_hardening_leapsectz: "right/UTC"
ntp_hardening_logdir: /var/log/chrony
ntp_hardening_logchange: 0.5
