---
- name: Common | Configure PAM for SSHD - bypass service accounts group
  community.general.pamd:
    name: sshd
    type: auth
    control: "[success=1 default=ignore]"
    module_path: pam_succeed_if.so
    arguments: user ingroup {{ pam_mfa_service_bypass_group }}
  tags: [enforce]

- name: Common | Configure PAM for SSHD - primary U2F/FIDO2
  community.general.pamd:
    name: sshd
    type: auth
    control: required
    module_path: "{{ pam_mfa_pam_module_u2f }}"
    arguments: authfile={{ pam_mfa_u2f_keys_path }} cue
  tags: [enforce]

- name: Common | Configure PAM for SSHD - backup TOTP
  community.general.pamd:
    name: sshd
    type: auth
    control: sufficient
    module_path: "{{ pam_mfa_pam_module_google_authenticator }}"
    arguments: nullok user_readenv=1 secret={{ pam_mfa_totp_dir }}/%u
  when: pam_mfa_totp_enabled
  tags: [enforce]

- name: Common | Configure PAM for sudo - enforce MFA
  community.general.pamd:
    name: sudo
    type: auth
    control: required
    module_path: "{{ pam_mfa_pam_module_u2f }}"
    arguments: authfile={{ pam_mfa_u2f_keys_path }} cue
  tags: [enforce]

- name: Common | Configure PAM for sudo - backup TOTP
  community.general.pamd:
    name: sudo
    type: auth
    control: sufficient
    module_path: "{{ pam_mfa_pam_module_google_authenticator }}"
    arguments: nullok user_readenv=1 secret={{ pam_mfa_totp_dir }}/%u
  when: pam_mfa_totp_enabled
  tags: [enforce]
